server {
    listen 80;
    server_name _;
    root /var/www/html/public;

    client_max_body_size 1024m;

    index index.php;

    location ~ ^/api/analyses/[0-9]+/events$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root/index.php;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_pass app:9000;

        fastcgi_buffering off;
        fastcgi_request_buffering off;
        gzip off;

        add_header X-Accel-Buffering no;
        add_header Cache-Control "no-cache";
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass app:9000;
        fastcgi_read_timeout 300;
    }

    location ~* \.(?:css|js|png|jpg|jpeg|gif|svg|ico)$ {
        expires 7d;
        access_log off;
    }
}
